### PR TITLE
fix(sitemap): validate and parse properties

### PR DESCRIPTION
**Pull request by Haroenv**
The goal of this PR is to validate which values for the options are valid. I based myself on https://www.sitemaps.org/protocol.html

I was doubting to add a typing system, but I’m not sure if that would catch the need of having descriptive error messages.

## sidenote

before, because of using `&&` instead of checking `undefined` and `null`, a 0 given to priority would not be wrapped in its tag.

I noticed this change when updating the snapshots in #15

### CODE REVIEW

**Comment by vvo** [comment]
Is it undefined or null? I would only check for undefined. So that if the API consumer made a mistake in its own code he can see it.

If you want to go further, you could actually check the usage of the API and ensure you get a number. (whitelist and error instead of blacklist and ignore)

**Comment by Haroenv** [comment]
Good idea, but then every priority needs to be checked isNaN, won't that be a more expensive operation?

**Comment by mikaa123** [comment]
What about only adding the priority if `isNaN(priority)`?

**Comment by vvo** [comment]
> Good idea, but then every priority needs to be checked isNaN, won't that be a more expensive operation?

It may or may not, this is a very low level operation. Better always be explicit and check types and error appropriately rather than trying to be magic and solve bugs for the user (if he's passing something that's not a number, he may have a bug in his own code).

Since you are writing files on disk, the performance scale of this operation should be very minor compared to actual I/O.

**Comment by Haroenv** [comment]
Let's do that then, thanks for the insights!


Also someone else can do the update if I don't get to it

**Pull request merged**
